services:
  server:
    image: server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      SERVER_ENV: ${SERVER_ENV}
  
  pg-db:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - server-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: Dwoshada

volumes:
  server-db:
    external: true
    