services:
  server:
    image: server:v3
    ports:
      - 8080:8080
    environment:
      SERVER_ENV: DEV
  
  pg-db:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - /home/oshada/projects/ceyloninfo/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: dwoshada
    